server:
  port: 7001 # 服务端口

spring:
  application:
    name: lzhpo-zuul-gateway

eureka:
  client:
    registerWithEureka: true # 服务注册开关
    fetchRegistry: true # 服务发现开关
    serviceUrl: # 客户端(服务提供者)注册到哪一个Eureka Server服务注册中心，多个用逗号分隔
      # 单机版 Eureka 服务注册中心
      #defaultZone: http://localhost:6001/eureka
      # 集群版 Eureka 服务注册中心
      defaultZone: http://eureka6001.com:6001/eureka,http://eureka6002.com:6002/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port} # 指定实例ID,就不会显示主机名了
    preferIpAddress: true #访问路径可以显示IP地址

    ####################################################以下建议开发环境配置####################################################

    #心跳监测持续时间，测试的时候将值设置小一些，保证关闭注册中心能及时踢出服务，
    #Eureka客户端向服务端发送心跳的时间间隔：单位为秒（客户端告诉服务端自己会按照该规则）
    lease-renewal-interval-in-seconds: 1
    #Eureka客户端在收到最后一次心跳之后的等待时间上限：单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
    lease-expiration-duration-in-seconds: 2

###################################################Zuul#########################################################
zuul:
  routes:
    povider-product: # 路由名称，名称任意，保持所有路由名称唯一
      path: /product/** # 访问路径
      serviceId: lzhpo-product # 指定服务ID，会自动从Eureka中找到此服务的ip和端口
      stripPrefix: false # 代理转发时去掉前缀，false:代理转发时不去掉前缀 例如:为true时请求 /product/get/1，代理转发到/get/1