spring:
  profiles:
    active: dev # 激活开发环境配置
---
server:
  port: 6001 #端口号
spring:
  profiles: dev # 开发环境
  application:
    name: microservice-config-eureka
eureka:
  instance:
    #Eureka注册IP地址
    #hostname: eureka6001.com
    #Docker
    hostname: 192.168.200.115
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:6001/eureka/
  server:
    enable-self-preservation: false # 禁用自我保护机制*****************
---
server:
  port: 6001 #端口号
spring:
  profiles: prod # 生产环境
  application:
    name: microservice-config-eureka
eureka:
  instance:
    hostname: eureka6001.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka6001.com:6001/eureka/
  server:
    enable-self-preservation: true # 开启自我保护机制*****************